spring:
  datasource:
    url: jdbc:postgresql://ec2-3-34-48-181.ap-northeast-2.compute.amazonaws.com:2345/kt_dev
    username: ENC(YZNdt6MZddlwgUIo2WwLAYOhKaViEAvi)
    password: ENC(DzdOoSVsevuVYC+09c++2A==)
    maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

